### ISSUE TITLE
Nothing to Table.select(...) exception

### ISSUE THREAD

**Issue by sp-guillem-orpinell** [socialpoint-labs/sheetfu-apps-script#13]
In case Table.select(...) does not have any value to match, function is not considering the exception.

Thus, Table.select().first() is crashing as...
`GridArray.prototype.first = function() {
  return this[0]
};`

I'd use a throw as an exception, so developers could handle it with a try..catch if needed.

**Comment by sp-ricard-valverde** [comment]
The popular _Django_ framework for _Python_ does return a ```None```value in this case([link](https://docs.djangoproject.com/en/2.0/ref/models/querysets/#django.db.models.query.QuerySet.first)). I would do the same and return an ```undefined```

**Comment by sp-philippe-oger** [comment]
So does SQLAlchemy apparently: http://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.orm.query.Query.first
Adding this now.
