### ISSUE TITLE
Remove row

### ISSUE THREAD

**Issue by andrewmiller1** [socialpoint-labs/sheetfu-apps-script#23]
As far as I can see, you can add but not delete. This makes working with a table difficult. It's good practice to add opposites for each function in general as well

**Comment by philippe2803** [comment]
There are some challenges into deleting rows, and guarantee data consistency, especially if you commit your data at the row level. I looked into it some time ago, I would like to look into it again soon.

For the time being, you could have a field "active" in your table, which you then can use to filter your data using the select method.

I'll leave the issue open to remind me later to add it.

**Comment by andrewmiller1** [comment]
Awesome - thanks for looking into this :)

**Comment by philippe2803** [comment]
@andrewmiller1 we are about to have this feature added.  @glecko is taking care of it.
You can follow the current PR for this here https://github.com/socialpoint-labs/sheetfu-apps-script/pull/30.

**Comment by philippe2803** [comment]
#30
