### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xandyxor** [socialpoint-labs/sheetfu-apps-script#24]
If the value of the field in the form is the date
like this table:
day ,             name , money
2018-08-14, andy , 123456
2018-08-15, andy, 234567

and then code

var item = table.select({"day": "2018-08-14"}).first();

it will report an error: 
TypeError: 2018-08-14 物件中沒有 getTime 函式。 (第 221 行，檔案名稱：Table，專案名稱：Sheetfu)
maybe english version:
TypeError: 2018-08-14 There is no getTime function in the object. (Line 221, file name: Table, project name: Sheetfu)

https://github.com/socialpoint-labs/sheetfu/blob/5a6a49db1c7aa2de7ba2286c1b8edc3b448174d5/Table.gs#L221

if(currentRow.getFieldValue(label).getTime() !== filterObject[label].getTime()) {

**Comment by philippe2803** [comment]
This is because you are comparing the dates object of your table with a string. It does not find the getTime() method because you gave it a string, and not a date object.

Try this:

```javascript
var targetDate = new Date("2018-08-14");
var item = table.select({"day": targetDate}).first();
```

Let me know if this works.
