### ISSUE TITLE
Default headerRow never works. Typo?

### ISSUE THREAD

**Issue by ysslang** [socialpoint-labs/sheetfu-apps-script#25]
https://github.com/socialpoint-labs/sheetfu/blob/5a6a49db1c7aa2de7ba2286c1b8edc3b448174d5/Table.gs#L9

Use `typeof headerRow === "undefined"` or `headerRow === undefined` will be fine.

**Comment by sp-guillem-orpinell** [comment]
Yeap... doesn't work for me neither!
