### ISSUE TITLE
Multiple row header and excluding footer

### ISSUE THREAD

**Issue by dev1337** [socialpoint-labs/sheetfu-apps-script#41]
Is there a way I can do the following with Sheetfu?

- specify a header that is more then 1 row thick (merged rows)
- specify a footer so that its excluded from the items

**Comment by glecko** [comment]
They would be nice additions but I don't think they go very in-line of the philosophy of Sheetfu of using sheets as database tables.

The implementation would be very easy, but I'm not sure the added code complexity compensates the few cases where this would be used.

**Comment by dev1337** [comment]
I see. I built my own methods around some of the Sheetfu ones that allow me to specify these, so I guess this issue can be closed now.
